from ampal.specifications.polymer_specs.ta_polypeptide import TAPolypeptide
from ampal.specifications.polymer_specs.helix import Helix, HelicalHelix
from ampal.specifications.polymer_specs.nucleic_acid_strand import NucleicAcidStrand