#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


python -m unittest discover unit_tests/.

if [ $? -eq 1 ]
then
  echo "Unit tests failed while committing ISAMBARD, please check them and recommit."
  exit 1
else
  echo "ISAMBARD unit tests passed, committing."
fi

exit 0
