from ampal.specifications.assembly_specs.solenoid import HelixPair, Solenoid
from ampal.specifications.assembly_specs.coiledcoil import CoiledCoil
from ampal.specifications.assembly_specs.nucleic_acid_duplex import DNADuplex